name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  upload:
    name: Generate Build Artifacts

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [dev]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Build
      run: make >
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: notec-${{ matrix.os }}-${{ matrix.version }}
        path: notec